version: '3'

services:
    web:
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile
        container_name: plugin-outbound-call
        ports:
            - 3000:3000
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        working_dir: /app

volumes:
    node_modules:
